# Generated by Django 5.2.14 on 2026-05-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_normalized', models.CharField(db_index=True, max_length=255)),
                ('csfd_url', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('title_normalized', models.CharField(db_index=True, max_length=255)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('csfd_url', models.URLField(unique=True)),
                ('actors', models.ManyToManyField(related_name='films', to='movies.actor')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
